name: Test
on:
  - push

jobs:
  check-config:
    name: Check Configuration
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Carvel
        uses: vmware-tanzu/carvel-setup-action@v1.1.1
        with:
          only: ytt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check configuration
        run: |
          make check
  test-package:
    name: Test Package
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Carvel
        uses: vmware-tanzu/carvel-setup-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create kind cluster
        run: |
          # Initialize brew because of https://github.com/actions/runner-images/issues/6283
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install kind
          kind create cluster

          # Wait for the generation of a token for the Service Account
          while [ $(kubectl get configmap kube-root-ca.crt --no-headers | wc -l) -eq 0 ] ; do
            sleep 3
          done

      - name: Run tests
        run: |
          chmod +x test/test.sh
          test/test.sh
